spring.application.name=Midnight-Technician

server.port=8080

# Security
security.cookies.secure=true
security.cookies.domain=htp://localhost:8080

# JWT Configuration
jwt.secret=${JWT_SECRET:changeItAsSoonAsPossibleBeforeProductionOrAnythingReallyThisIsNotGood}
jwt.issuer=midnight-technician-website
jwt.audience=midnight-technician-users
jwt.access-ttl-minutes=15
jwt.clock-skew-seconds=15
jwt.refresh-ttl-days=14
refresh.pepper=${REFRESH_TOKEN_PEPPER:changeIt}

# LOGGING
logging.level.root=INFO
logging.level.dev.midnightcoder=DEBUG
logging.level.org.springframework.web=INFO
logging.file.name=./logs/MidnightTechnician-Log.log

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5499/midnight_database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:changeIt}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
